<a href="https://colab.research.google.com/github/Sshubam/PyTorch-Code/blob/main/PyTorch_11_understanding_RNN_shapes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
N = 1
T = 10
D = 3
M = 5
K = 2
X = np.random.randn(N, T, D)

In [ ]:
X

array([[[ 0.58000334, -0.06914095,  1.14470997],
        [-0.69689015, -0.86975093, -0.59115776],
        [ 0.20440894,  0.48976944, -0.18179138],
        [ 0.51348737,  1.21080924, -0.59365223],
        [ 1.11281428, -0.93358827, -0.37414766],
        [-1.65361134, -1.71777051, -1.39071671],
        [ 0.476168  ,  0.49235149,  0.72178638],
        [ 2.17770843, -0.42823937,  0.30950953],
        [-0.84159845, -0.77408767, -0.68714487],
        [-1.21662167,  0.24041689, -1.31905917]]])

In [ ]:
# N = number of samples
# T = length of sequence
# D = number of input features
# M = number of hidden units
# K = number of output units

In [ ]:
class SimpleRNN(nn.Module):
  def __init__(self, n_inputs, n_hidden, n_outputs):
    super(SimpleRNN, self).__init__()
    self.D = n_inputs
    self.M = n_hidden
    self.K = n_outputs
    self.rnn = nn.RNN(
        input_size=self.D,
        hidden_size=self.M,
        nonlinearity='tanh',
        batch_first=True )
    self.fc = nn.Linear(self.M, self.K)

  def forward(self, X):
    h0 = torch.zeros(1, X.size(0), self.M)
    out, _ = self.rnn(X, h0)
    out = self.fc(out)
    return out

In [ ]:
model = SimpleRNN(n_inputs=D, n_hidden=M, n_outputs=K)

In [ ]:
inputs = torch.from_numpy(X.astype(np.float32))
out = model(inputs)
out 

tensor([[[-0.0580, -0.4716],
         [-0.1531, -0.4975],
         [ 0.0101, -0.4328],
         [ 0.1612, -0.4133],
         [ 0.0333, -0.4950],
         [-0.2407, -0.3300],
         [ 0.0497, -0.4649],
         [ 0.0978, -0.5957],
         [-0.1135, -0.3581],
         [-0.0056, -0.3442]]], grad_fn=<AddBackward0>)

In [ ]:
out.shape

torch.Size([1, 10, 2])

In [ ]:
#Save array for later
Yhats_torch = out.detach().numpy()

In [ ]:
W_xh, W_hh, b_xh, b_hh = model.rnn.parameters()

In [ ]:
W_xh.shape

torch.Size([5, 3])

In [ ]:
W_xh

Parameter containing:
tensor([[-0.4446,  0.2872,  0.2413],
        [-0.0745, -0.0561,  0.2492],
        [-0.0588, -0.1631,  0.0148],
        [ 0.0279, -0.3228, -0.0256],
        [ 0.1044, -0.1830,  0.4052]], requires_grad=True)

In [ ]:
W_xh = W_xh.data.numpy()
W_xh

array([[-0.4446196 ,  0.28716502,  0.24132152],
       [-0.0744513 , -0.05611351,  0.24918744],
       [-0.05884463, -0.16307223,  0.01478294],
       [ 0.02790772, -0.3227859 , -0.02555762],
       [ 0.10436749, -0.18300356,  0.40519956]], dtype=float32)

In [ ]:
#Convert to NumPy arrays
b_xh = b_xh.data.numpy()
W_hh = W_hh.data.numpy()
b_hh = b_hh.data.numpy()

In [ ]:
W_xh.shape, b_xh.shape, W_hh.shape, b_hh.shape

((5, 3), (5,), (5, 5), (5,))

In [ ]:
Wo, bo = model.fc.parameters()

In [ ]:
Wo = Wo.data.numpy()
bo = bo.data.numpy()
Wo.shape, bo.shape

((2, 5), (2,))